### ISSUE TITLE
K8S Cluster Upgrade and Connectivity Problems with Talosctl

### ISSUE THREAD

**Issue by vaceslav** [hcloud-talos/terraform-hcloud-talos#142]
#### **Environment Details**
- Freshly installed K8S cluster using the following Terraform configuration:
    ```hcl
    module "talos" {
      source  = "hcloud-talos/talos/hcloud"
      version = "v2.12.0"

      talos_version      = "v1.8.4"
      kubernetes_version = "1.31.1"
      ...
    }
    ```

#### **Problem Description**

1. **Terraform's Kubernetes Version Parameter**
   - Updating the `kubernetes_version` in the Terraform configuration does not seem to have any effect. 
   - I understand this is expected, and the Kubernetes version must be updated using the `talosctl` command.

2. **Version Check Behavior**
   - Exported the Talos configuration and verified the version using:
     ```bash
     talosctl --talosconfig $TALOSCONFIG --nodes <control-plane-ip> version
     ```
   - Results:
     - Sometimes the output is as expected:
       ```
       Client:
               Tag:         v1.8.4
               SHA:         undefined
               Built:       2024-12-12T18:49:17Z
               Go version:  go1.23.4
               OS/Arch:     darwin/arm64
       Server:
               NODE:        <control-plane-ip>
               Tag:         v1.8.4
               SHA:         3c151c8a
               Built:       
               Go version:  go1.22.10
               OS/Arch:     linux/arm64
               Enabled:     RBAC
       ```
     - Frequently, however, I encounter the following error:
       ```
       Client:
               Tag:         v1.8.4
               SHA:         undefined
               Built:       2024-12-12T18:49:17Z
               Go version:  go1.23.4
               OS/Arch:     darwin/arm64
       Server:
       error getting version: 1 error occurred:
               * <control-plane-ip>: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp <control-plane-ip>:50000: i/o timeout"
       ```

3. **Upgrade Kubernetes Version**
   - Attempted to upgrade Kubernetes version using the following command:
     ```bash
     talosctl --talosconfig $TALOSCONFIG --nodes <control-plane-ip> upgrade-k8s --to 1.31.3
     ```
   - The upgrade process fails, and I observe two different errors intermittently:

     **Error 1:**
     ```
     error detecting the lowest Kubernetes version Get "https://kube.cluster.local:6443/api/v1/namespaces/kube-system/pods": dial tcp: lookup kube.cluster.local: no such host
     ```

     **Error 2:**
     ```
     error detecting the lowest Kubernetes version error building kubernetes client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp <control-plane-ip>:50000: i/o timeout"
     ```

#### **Expected Behavior**
- Changing the `kubernetes_version` in Terraform should either:
  - Reflect in the deployed cluster, or
  - Be clearly documented as unsupported, requiring manual intervention.
- The `talosctl` commands should reliably interact with the cluster for both version checks and upgrades.

---

### **Questions**
1. How can I ensure reliable connectivity to the cluster using `talosctl`?
2. What is the proper way to upgrade the Kubernetes version in this setup?
3. Are there any known issues or prerequisites I might be missing that cause the `rpc error` or DNS resolution failures?

---

**Comment by mrclrchtr** [comment]
1.
When did you set up the cluster? There was a problem that the floating IP was used instead of a fixed IP in the Talosconfig. 

Fixed here: https://github.com/hcloud-talos/terraform-hcloud-talos/commit/41bcbfa124c09d5963ebd5323c2e3d24b95e94ab

Please check the IP in talosconfig.
This could explain the connection error. But it does not have to.

2.
This is quite simple and stable: https://www.talos.dev/v1.9/kubernetes-guides/upgrading-kubernetes/

3.
Not that I'm aware of.

**Comment by vaceslav** [comment]
I encountered the following error when working with Kubernetes:

```
error detecting the lowest Kubernetes version 
error building kubernetes client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp <control-plane-ip>:50000: i/o timeout"
```

Observations:
1. This error seems to be related to a firewall configuration. When I extend the Hetzner firewall rules to allow traffic from any IPv4 and any IPv6 address, the timeout issue disappears.
2.	My operating system is macOS.

**Persistent Issue**

Even after resolving the timeout, another error persists:

```
error detecting the lowest Kubernetes version 
Get "https://kube.cluster.local:6443/api/v1/namespaces/kube-system/pods": dial tcp: lookup kube.cluster.local: no such host
```

I followed the [official Talos documentation](https://www.talos.dev/v1.9/kubernetes-guides/upgrading-kubernetes/) and executed the command:

`talosctl --nodes <control-plane-ip> upgrade-k8s --to 1.31.3`

However, I encountered the following error:

```
error detecting the lowest Kubernetes version 
Get "https://kube.cluster.local:6443/api/v1/namespaces/kube-system/pods": dial tcp: lookup kube.cluster.local: no such host
```

Problem

Due to the above error, the Kubernetes update is not possible.

**Comment by mrclrchtr** [comment]
I am very sorry for the late feedback. Unfortunately, I didn't have time to take a closer look.

I can not explain the firewall issues.
And somehow `kube.cluster.local` cannot be resolved.

Can you show me the machine configs (especially the extra_host_entries)? Please hide sensitive data.

My first thought is that the traffic is somehow going through the public interfaces instead of the private ones.

**Comment by WebSpider** [comment]
> And somehow `kube.cluster.local` cannot be resolved.

I just experienced this as well. `kube.cluster.local` seems to be the default API hostname for the cluster, which is unresolveable from outside the cluster.

To overcome this, I upgraded with:

`talosctl --nodes <node i want to upgrade> upgrade-k8s --endpoint https://cluster-api-lb-ip:6443 --dry-run`

**Comment by mrclrchtr** [comment]
Yes, it's an "internal" used hostname. `cluster_api_host` has to be used for external communication.

Copied from Docs:
- **Public API Endpoint:**
    - You can define a stable public endpoint for your cluster using the `cluster_api_host` variable (
      e.g., `kube.mydomain.com`).
    - If you set `cluster_api_host`, you **must** create a DNS A record for this hostname pointing to the public IP
      address you want clients to use. This could be:
        - The Hetzner Floating IP (if `enable_floating_ip = true`).
        - The IP of an external Load Balancer you configure separately.
        - The public IP of a specific control plane node (less recommended for multi-node control planes).
    - The generated `kubeconfig` and `talosconfig` will use this hostname
      if `output_mode_config_cluster_endpoint = "cluster_endpoint"`.
- **Internal API Endpoint:**
    - For internal communication *between cluster nodes*, Talos often uses the hostname `kube.[cluster_domain]` (
      e.g., `kube.cluster.local`).
    - If `enable_alias_ip = true` (the default), this module automatically configures `/etc/hosts` entries on each node
      to resolve `kube.[cluster_domain]` to the *private* alias IP (`10.0.1.100` by default). This ensures reliable
      internal communication.

I will improve the docs and add the information, that `Internal API Endpoint` is used in talos and kube config, if no `cluster_api_host` is set.

**Comment by mrclrchtr** [comment]
I'm going to close this - feel free to reopen again, if required
